### ISSUE TITLE
card mod doesnt seem to apply to this card

### ISSUE THREAD

**Issue by mcrummett** [Gh61/lovelace-hue-like-light-card#21] opened 2023-04-15 20:04 UTC
For some reason card_mod doesn't seem to apply properly to this card?  When i do the below, the height is correct whilst in the configuration screen but no longer applies when viewing the dashboard normally.

```
card_mod:
  style: |
    ha-card { 
    min-height: 600px
    }
```

**Comment by Gh61** [comment] 2023-04-15 20:53
Duplicate of #18.
Is already fixed, will be released in future version.

**Comment by mcrummett** [comment] 2023-04-15 20:55
Ah sorry for the duplicate. Cheers!

**Closed** 2023-04-15 20:55 UTC
