### ISSUE TITLE
Wrong entity name crash the lovelace page instead of returning error

### ISSUE THREAD

**Issue by Pinky007** [Gh61/lovelace-hue-like-light-card#33] opened 2023-07-28 22:52 UTC
Hi,

Running the latest HA:
![grafik](https://github.com/Gh61/lovelace-hue-like-light-card/assets/1488257/7a912360-2d5f-46e8-b6ab-de6373a25a22)
and latest release of the card through HACS.

Got a lovelace sub page with my lights:
![grafik](https://github.com/Gh61/lovelace-hue-like-light-card/assets/1488257/dc0159ad-788f-4672-9cc9-2ebf82942174)

But if an entity is wrongly spelled, the lovelace page just crash with no error message:
![grafik](https://github.com/Gh61/lovelace-hue-like-light-card/assets/1488257/e4a238af-7ebb-4208-a476-d5d441a70db2)

Was finally able to find the bug through the web developer checks:
![grafik](https://github.com/Gh61/lovelace-hue-like-light-card/assets/1488257/d76a0486-46b4-4ad2-84e1-0bd54d4df929)

Hope this helps for the development :)
Let me know if you need any other information!

**Comment by Gh61** [comment] 2023-09-17 11:16
Hi, thank you for reporting.

Sadly, I cannot reproduce this error state. Can you please verify, this error is still happening in the latest version.
If so, can you please post configuration of your whole view in YAML, in here?
If the error no longer occurs, feel free to close this issue.

Thank you.

**Closed** 2023-11-02 15:26 UTC
