### ISSUE TITLE
Cant choose just one light source in color wheel

### ISSUE THREAD

**Issue by Huxi2111** [Gh61/lovelace-hue-like-light-card#295] opened 2024-11-24 10:34 UTC
When multiple light sources in an area have the same color, they are grouped together in the color wheel, which is great. However, if I try to change the color of just one of them, I have to do it very quickly because they automatically “group” back together.

https://github.com/user-attachments/assets/fec04a60-728a-4e91-b8b3-6afef3ea0a6c

**Comment by Gh61** [comment] 2024-11-25 13:55
Thank you for reporting this issue.
I believe, it's the same issue as mentioned here:
https://github.com/Gh61/lovelace-hue-like-light-card/issues/253

Or at least it has the same reason.

This must be the first issue, to be solved in the next release, as it's really annoying to use.

I believe, the refresh interval of UI is based on the performance of machine running HA.
In my experience (on some old RPi 2), the refresh happens every few seconds, which is enough to change the color of the light.
It seems that refresh on your system is happening at least every second, making the color change of single light almost impossible and very annoying.

Closing as duplicate of issue #253.
Feel free to continue there, or if you thing this is independent issue, you can reopen this one.

**Closed by Gh61** 2024-11-25 13:55 UTC

**Comment by Huxi2111** [comment] 2024-11-25 14:03
Hey

Just wanted to let you know that im running on a rpi 5 8GB.

But sounds perfect if the fix, comes in the nest release.

Fra: Tomáš Zenkner ***@***.***>
Sendt: 25. november 2024 14:56
Til: Gh61/lovelace-hue-like-light-card ***@***.***>
Cc: Mads Hansen ***@***.***>; Author ***@***.***>
Emne: Re: [Gh61/lovelace-hue-like-light-card] Cant choose just one light source in color wheel (Issue #295)


Thank you for reporting this issue.
I believe, it's the same issue as mentioned here:
#253<https://github.com/Gh61/lovelace-hue-like-light-card/issues/253>

Or at least it has the same reason.

This must be the first issue, to be solved in the next release, as it's really annoying to use.

I believe, the refresh interval of UI is based on the performance of machine running HA.
In my experience (on some old RPi 2), the refresh happens every few seconds, which is enough to change the color of the light.
It seems that refresh on your system is happening at least every second, making the color change of single light almost impossible and very annoying.

Closing as duplicate of issue #253<https://github.com/Gh61/lovelace-hue-like-light-card/issues/253>.
Feel free to continue there, or if you thing this is independent issue, you can reopen this one.
